name: Build/release

on:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - main

jobs:
  release:
    env: 
      GITHUB_TOKEN: ${{ secrets.github_token }}
      
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest] 
        
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    
    - name: Build/release Electron app
      uses: leguass7/action-electron-forge@v1
      with:
        github_token: ${{ secrets.github_token }}
        release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        
